//Использование в коммерческих целях запрещено.
//Наказание - неминуемый кряк и распространение по всему инет.
//Business application is forbidden.
//Punishment - unavoidable crack and propagation on everything inet.
unit MD5;


interface

uses Windows;


var
     MD5buf : Array[0..3] of Dword;
//     MD5inb : Array[0..63] of Byte;

procedure MD5Init;
procedure MD5Transform(Buffer: pointer); assembler;

implementation

procedure MD5Init;
begin
        MD5buf[0] := $67452301;
        MD5buf[1] := $efcdab89;
        MD5buf[2] := $98badcfe;
        MD5buf[3] := $10325476;
end;

procedure MD5Transform(Buffer: pointer); assembler;
asm
       push    ebx   // store registers, must be preserved,
       push    esi   //  as Delphi compiler required
       push    edi
       push    ebp

       // let edi points to A,B,C,D chaining variables array
       lea edi, MD5buf

       // let esi points to transformed Buffer
       mov esi, eax

       // include md4asm transform code
                mov     eax, [edi]
                mov     ebx, [edi+4]
                push    edi
                mov     ecx, [edi+8]
                mov     edx, [edi+0Ch]
                mov     edi, ecx
                mov     ebp, [esi]
                xor     edi, edx
                lea     eax, [eax+ebp-28955B88h]
                and     edi, ebx
                mov     ebp, [esi+4]
                xor     edi, edx
                add     eax, edi
                mov     edi, ebx
                rol     eax, 7
                xor     edi, ecx
                add     eax, ebx
                lea     edx, [edx+ebp-173848AAh]
                and     edi, eax
                mov     ebp, [esi+8]
                xor     edi, ecx
                add     edx, edi
                mov     edi, eax
                rol     edx, 0Ch
                xor     edi, ebx
                add     edx, eax
                lea     ecx, [ecx+ebp+242070DBh]
                and     edi, edx
                mov     ebp, [esi+0Ch]
                xor     edi, ebx
                add     ecx, edi
                mov     edi, edx
                ror     ecx, 0Fh
                xor     edi, eax
                add     ecx, edx
                lea     ebx, [ebx+ebp-3E423112h]
                and     edi, ecx
                mov     ebp, [esi+10h]
                xor     edi, eax
                add     ebx, edi
                mov     edi, ecx
                ror     ebx, 0Ah
                xor     edi, edx
                add     ebx, ecx
                lea     eax, [eax+ebp-0A83F051h]
                and     edi, ebx
                mov     ebp, [esi+14h]
                xor     edi, edx
                add     eax, edi
                mov     edi, ebx
                rol     eax, 7
                xor     edi, ecx
                add     eax, ebx
                lea     edx, [edx+ebp+4787C62Ah]
                and     edi, eax
                mov     ebp, [esi+18h]
                xor     edi, ecx
                add     edx, edi
                mov     edi, eax
                rol     edx, 0Ch
                xor     edi, ebx
                add     edx, eax
                lea     ecx, [ecx+ebp-57CFB9EDh]
                and     edi, edx
                mov     ebp, [esi+1Ch]
                xor     edi, ebx
                add     ecx, edi
                mov     edi, edx
                ror     ecx, 0Fh
                xor     edi, eax
                add     ecx, edx
                lea     ebx, [ebx+ebp-2B96AFFh]
                and     edi, ecx
                mov     ebp, [esi+20h]
                xor     edi, eax
                add     ebx, edi
                mov     edi, ecx
                ror     ebx, 0Ah
                xor     edi, edx
                add     ebx, ecx
                lea     eax, [eax+ebp+698098D8h]
                and     edi, ebx
                mov     ebp, [esi+24h]
                xor     edi, edx
                add     eax, edi
                mov     edi, ebx
                rol     eax, 7
                xor     edi, ecx
                add     eax, ebx
                lea     edx, [edx+ebp-74BB0851h]
                and     edi, eax
                mov     ebp, [esi+28h]
                xor     edi, ecx
                add     edx, edi
                mov     edi, eax
                rol     edx, 0Ch
                xor     edi, ebx
                add     edx, eax
                lea     ecx, [ecx+ebp-0A44Fh]
                and     edi, edx
                mov     ebp, [esi+2Ch]
                xor     edi, ebx
                add     ecx, edi
                mov     edi, edx
                ror     ecx, 0Fh
                xor     edi, eax
                add     ecx, edx
                lea     ebx, [ebx+ebp-76A32842h]
                and     edi, ecx
                mov     ebp, [esi+30h]
                xor     edi, eax
                add     ebx, edi
                mov     edi, ecx
                ror     ebx, 0Ah
                xor     edi, edx
                add     ebx, ecx
                lea     eax, [eax+ebp+6B901122h]
                and     edi, ebx
                mov     ebp, [esi+34h]
                xor     edi, edx
                add     eax, edi
                mov     edi, ebx
                rol     eax, 7
                xor     edi, ecx
                add     eax, ebx
                lea     edx, [edx+ebp-2678E6Dh]
                and     edi, eax
                mov     ebp, [esi+38h]
                xor     edi, ecx
                add     edx, edi
                mov     edi, eax
                rol     edx, 0Ch
                xor     edi, ebx
                add     edx, eax
                lea     ecx, [ecx+ebp-5986BC72h]
                and     edi, edx
                mov     ebp, [esi+3Ch]
                xor     edi, ebx
                add     ecx, edi
                mov     edi, edx
                ror     ecx, 0Fh
                xor     edi, eax
                add     ecx, edx
                lea     ebx, [ebx+ebp+49B40821h]
                and     edi, ecx
                mov     ebp, [esi+4]
                xor     edi, eax
                add     ebx, edi
                mov     edi, ecx
                ror     ebx, 0Ah
                xor     edi, edx
                add     ebx, ecx
                mov     edi, ecx
                xor     edi, ebx
                lea     eax, [eax+ebp-9E1DA9Eh]
                and     edi, edx
                mov     ebp, [esi+18h]
                xor     edi, ecx
                add     eax, edi
                mov     edi, ebx
                rol     eax, 5
                add     eax, ebx
                xor     edi, eax
                lea     edx, [edx+ebp-3FBF4CC0h]
                and     edi, ecx
                mov     ebp, [esi+2Ch]
                xor     edi, ebx
                add     edx, edi
                mov     edi, eax
                rol     edx, 9
                add     edx, eax
                xor     edi, edx
                lea     ecx, [ecx+ebp+265E5A51h]
                and     edi, ebx
                mov     ebp, [esi]
                xor     edi, eax
                add     ecx, edi
                mov     edi, edx
                rol     ecx, 0Eh
                add     ecx, edx
                xor     edi, ecx
                lea     ebx, [ebx+ebp-16493856h]
                and     edi, eax
                mov     ebp, [esi+14h]
                xor     edi, edx
                add     ebx, edi
                mov     edi, ecx
                ror     ebx, 0Ch
                add     ebx, ecx
                xor     edi, ebx
                lea     eax, [eax+ebp-29D0EFA3h]
                and     edi, edx
                mov     ebp, [esi+28h]
                xor     edi, ecx
                add     eax, edi
                mov     edi, ebx
                rol     eax, 5
                add     eax, ebx
                xor     edi, eax
                lea     edx, [edx+ebp+2441453h]
                and     edi, ecx
                mov     ebp, [esi+3Ch]
                xor     edi, ebx
                add     edx, edi
                mov     edi, eax
                rol     edx, 9
                add     edx, eax
                xor     edi, edx
                lea     ecx, [ecx+ebp-275E197Fh]
                and     edi, ebx
                mov     ebp, [esi+10h]
                xor     edi, eax
                add     ecx, edi
                mov     edi, edx
                rol     ecx, 0Eh
                add     ecx, edx
                xor     edi, ecx
                lea     ebx, [ebx+ebp-182C0438h]
                and     edi, eax
                mov     ebp, [esi+24h]
                xor     edi, edx
                add     ebx, edi
                mov     edi, ecx
                ror     ebx, 0Ch
                add     ebx, ecx
                xor     edi, ebx
                lea     eax, [eax+ebp+21E1CDE6h]
                and     edi, edx
                mov     ebp, [esi+38h]
                xor     edi, ecx
                add     eax, edi
                mov     edi, ebx
                rol     eax, 5
                add     eax, ebx
                xor     edi, eax
                lea     edx, [edx+ebp-3CC8F82Ah]
                and     edi, ecx
                mov     ebp, [esi+0Ch]
                xor     edi, ebx
                add     edx, edi
                mov     edi, eax
                rol     edx, 9
                add     edx, eax
                xor     edi, edx
                lea     ecx, [ecx+ebp-0B2AF279h]
                and     edi, ebx
                mov     ebp, [esi+20h]
                xor     edi, eax
                add     ecx, edi
                mov     edi, edx
                rol     ecx, 0Eh
                add     ecx, edx
                xor     edi, ecx
                lea     ebx, [ebx+ebp+455A14EDh]
                and     edi, eax
                mov     ebp, [esi+34h]
                xor     edi, edx
                add     ebx, edi
                mov     edi, ecx
                ror     ebx, 0Ch
                add     ebx, ecx
                xor     edi, ebx
                lea     eax, [eax+ebp-561C16FBh]
                and     edi, edx
                mov     ebp, [esi+8]
                xor     edi, ecx
                add     eax, edi
                mov     edi, ebx
                rol     eax, 5
                add     eax, ebx
                xor     edi, eax
                lea     edx, [edx+ebp-3105C08h]
                and     edi, ecx
                mov     ebp, [esi+1Ch]
                xor     edi, ebx
                add     edx, edi
                mov     edi, eax
                rol     edx, 9
                add     edx, eax
                xor     edi, edx
                lea     ecx, [ecx+ebp+676F02D9h]
                and     edi, ebx
                mov     ebp, [esi+30h]
                xor     edi, eax
                add     ecx, edi
                mov     edi, edx
                rol     ecx, 0Eh
                add     ecx, edx
                xor     edi, ecx
                lea     ebx, [ebx+ebp-72D5B376h]
                and     edi, eax
                mov     ebp, [esi+14h]
                xor     edi, edx
                add     ebx, edi
                mov     edi, ecx
                ror     ebx, 0Ch
                add     ebx, ecx
                xor     edi, edx
                lea     eax, [eax+ebp-5C6BEh]
                xor     edi, ebx
                mov     ebp, [esi+20h]
                add     eax, edi
                rol     eax, 4
                lea     edx, [edx+ebp-788E097Fh]
                mov     edi, ebx
                add     eax, ebx
                xor     edi, ecx
                mov     ebp, [esi+2Ch]
                xor     edi, eax
                add     edx, edi
                mov     edi, eax
                rol     edx, 0Bh
                add     edx, eax
                xor     edi, ebx
                lea     ecx, [ecx+ebp+6D9D6122h]
                xor     edi, edx
                mov     ebp, [esi+38h]
                add     ecx, edi
                rol     ecx, 10h
                lea     ebx, [ebx+ebp-21AC7F4h]
                mov     edi, edx
                add     ecx, edx
                xor     edi, eax
                mov     ebp, [esi+4]
                xor     edi, ecx
                add     ebx, edi
                mov     edi, ecx
                ror     ebx, 9
                add     ebx, ecx
                xor     edi, edx
                lea     eax, [eax+ebp-5B4115BCh]
                xor     edi, ebx
                mov     ebp, [esi+10h]
                add     eax, edi
                rol     eax, 4
                lea     edx, [edx+ebp+4BDECFA9h]
                mov     edi, ebx
                add     eax, ebx
                xor     edi, ecx
                mov     ebp, [esi+1Ch]
                xor     edi, eax
                add     edx, edi
                mov     edi, eax
                rol     edx, 0Bh
                add     edx, eax
                xor     edi, ebx
                lea     ecx, [ecx+ebp-944B4A0h]
                xor     edi, edx
                mov     ebp, [esi+28h]
                add     ecx, edi
                rol     ecx, 10h
                lea     ebx, [ebx+ebp-41404390h]
                mov     edi, edx
                add     ecx, edx
                xor     edi, eax
                mov     ebp, [esi+34h]
                xor     edi, ecx
                add     ebx, edi
                mov     edi, ecx
                ror     ebx, 9
                add     ebx, ecx
                xor     edi, edx
                lea     eax, [eax+ebp+289B7EC6h]
                xor     edi, ebx
                mov     ebp, [esi]
                add     eax, edi
                rol     eax, 4
                lea     edx, [edx+ebp-155ED806h]
                mov     edi, ebx
                add     eax, ebx
                xor     edi, ecx
                mov     ebp, [esi+0Ch]
                xor     edi, eax
                add     edx, edi
                mov     edi, eax
                rol     edx, 0Bh
                add     edx, eax
                xor     edi, ebx
                lea     ecx, [ecx+ebp-2B10CF7Bh]
                xor     edi, edx
                mov     ebp, [esi+18h]
                add     ecx, edi
                rol     ecx, 10h
                lea     ebx, [ebx+ebp+4881D05h]
                mov     edi, edx
                add     ecx, edx
                xor     edi, eax
                mov     ebp, [esi+24h]
                xor     edi, ecx
                add     ebx, edi
                mov     edi, ecx
                ror     ebx, 9
                add     ebx, ecx
                xor     edi, edx
                lea     eax, [eax+ebp-262B2FC7h]
                xor     edi, ebx
                mov     ebp, [esi+30h]
                add     eax, edi
                rol     eax, 4
                lea     edx, [edx+ebp-1924661Bh]
                mov     edi, ebx
                add     eax, ebx
                xor     edi, ecx
                mov     ebp, [esi+3Ch]
                xor     edi, eax
                add     edx, edi
                mov     edi, eax
                rol     edx, 0Bh
                add     edx, eax
                xor     edi, ebx
                lea     ecx, [ecx+ebp+1FA27CF8h]
                xor     edi, edx
                mov     ebp, [esi+8]
                add     ecx, edi
                rol     ecx, 10h
                lea     ebx, [ebx+ebp-3B53A99Bh]
                mov     edi, edx
                add     ecx, edx
                xor     edi, eax
                mov     ebp, [esi]
                xor     edi, ecx
                add     ebx, edi
                mov     edi, edx
                ror     ebx, 9
                add     ebx, ecx
                xor     edi, 0FFFFFFFFh
                lea     eax, [eax+ebp-0BD6DDBCh]
                or      edi, ebx
                mov     ebp, [esi+1Ch]
                xor     edi, ecx
                add     eax, edi
                mov     edi, ecx
                rol     eax, 6
                add     eax, ebx
                xor     edi, 0FFFFFFFFh
                lea     edx, [edx+ebp+432AFF97h]
                or      edi, eax
                mov     ebp, [esi+38h]
                xor     edi, ebx
                add     edx, edi
                mov     edi, ebx
                rol     edx, 0Ah
                add     edx, eax
                xor     edi, 0FFFFFFFFh
                lea     ecx, [ecx+ebp-546BDC59h]
                or      edi, edx
                mov     ebp, [esi+14h]
                xor     edi, eax
                add     ecx, edi
                mov     edi, eax
                rol     ecx, 0Fh
                add     ecx, edx
                xor     edi, 0FFFFFFFFh
                lea     ebx, [ebx+ebp-36C5FC7h]
                or      edi, ecx
                mov     ebp, [esi+30h]
                xor     edi, edx
                add     ebx, edi
                mov     edi, edx
                ror     ebx, 0Bh
                add     ebx, ecx
                xor     edi, 0FFFFFFFFh
                lea     eax, [eax+ebp+655B59C3h]
                or      edi, ebx
                mov     ebp, [esi+0Ch]
                xor     edi, ecx
                add     eax, edi
                mov     edi, ecx
                rol     eax, 6
                add     eax, ebx
                xor     edi, 0FFFFFFFFh
                lea     edx, [edx+ebp-70F3336Eh]
                or      edi, eax
                mov     ebp, [esi+28h]
                xor     edi, ebx
                add     edx, edi
                mov     edi, ebx
                rol     edx, 0Ah
                add     edx, eax
                xor     edi, 0FFFFFFFFh
                lea     ecx, [ecx+ebp-100B83h]
                or      edi, edx
                mov     ebp, [esi+4]
                xor     edi, eax
                add     ecx, edi
                mov     edi, eax
                rol     ecx, 0Fh
                add     ecx, edx
                xor     edi, 0FFFFFFFFh
                lea     ebx, [ebx+ebp-7A7BA22Fh]
                or      edi, ecx
                mov     ebp, [esi+20h]
                xor     edi, edx
                add     ebx, edi
                mov     edi, edx
                ror     ebx, 0Bh
                add     ebx, ecx
                xor     edi, 0FFFFFFFFh
                lea     eax, [eax+ebp+6FA87E4Fh]
                or      edi, ebx
                mov     ebp, [esi+3Ch]
                xor     edi, ecx
                add     eax, edi
                mov     edi, ecx
                rol     eax, 6
                add     eax, ebx
                xor     edi, 0FFFFFFFFh
                lea     edx, [edx+ebp-1D31920h]
                or      edi, eax
                mov     ebp, [esi+18h]
                xor     edi, ebx
                add     edx, edi
                mov     edi, ebx
                rol     edx, 0Ah
                add     edx, eax
                xor     edi, 0FFFFFFFFh
                lea     ecx, [ecx+ebp-5CFEBCECh]
                or      edi, edx
                mov     ebp, [esi+34h]
                xor     edi, eax
                add     ecx, edi
                mov     edi, eax
                rol     ecx, 0Fh
                add     ecx, edx
                xor     edi, 0FFFFFFFFh
                lea     ebx, [ebx+ebp+4E0811A1h]
                or      edi, ecx
                mov     ebp, [esi+10h]
                xor     edi, edx
                add     ebx, edi
                mov     edi, edx
                ror     ebx, 0Bh
                add     ebx, ecx
                xor     edi, 0FFFFFFFFh
                lea     eax, [eax+ebp-8AC817Eh]
                or      edi, ebx
                mov     ebp, [esi+2Ch]
                xor     edi, ecx
                add     eax, edi
                mov     edi, ecx
                rol     eax, 6
                add     eax, ebx
                xor     edi, 0FFFFFFFFh
                lea     edx, [edx+ebp-42C50DCBh]
                or      edi, eax
                mov     ebp, [esi+8]
                xor     edi, ebx
                add     edx, edi
                mov     edi, ebx
                rol     edx, 0Ah
                add     edx, eax
                xor     edi, 0FFFFFFFFh
                lea     ecx, [ecx+ebp+2AD7D2BBh]
                or      edi, edx
                mov     ebp, [esi+24h]
                xor     edi, eax
                add     ecx, edi
                mov     edi, eax
                rol     ecx, 0Fh
                add     ecx, edx
                xor     edi, 0FFFFFFFFh
                lea     ebx, [ebx+ebp-14792C6Fh]
                or      edi, ecx
                xor     edi, edx
                add     ebx, edi
                ror     ebx, 0Bh
                add     ebx, ecx
                pop     edi
                add     [edi], eax
                add     [edi+4], ebx
                add     [edi+8], ecx
                add     [edi+0Ch], edx

       pop     ebp   // restore saved registers
       pop     edi
       pop     esi
       pop     ebx
end;

end.
